# Generated by Django 5.2.16 on 2026-07-27 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('memo', models.TextField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('scope_kind', models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], max_length=10)),
                ('scope_value', models.CharField(max_length=20)),
                ('rolled_from_kind', models.CharField(blank=True, choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], max_length=10, null=True)),
                ('rolled_from_value', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.CharField(max_length=32)),
                ('completed_at', models.CharField(blank=True, max_length=32, null=True)),
                ('time', models.CharField(blank=True, max_length=5, null=True)),
                ('subtasks', models.JSONField(blank=True, default=list)),
                ('repeat_weekdays', models.JSONField(blank=True, null=True)),
                ('excluded_dates', models.JSONField(blank=True, null=True)),
                ('priority', models.BooleanField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('background', models.BooleanField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repeat_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='tasks_task_user_id_0b1849_idx')],
            },
        ),
    ]
