# Generated by Django 5.2.16 on 2026-07-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
