# Generated by Django 5.2.16 on 2026-07-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='rolled_from_kind',
            field=models.CharField(blank=True, choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year'), ('bucket', 'bucket')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='scope_kind',
            field=models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year'), ('bucket', 'bucket')], max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='scope_value',
            field=models.CharField(max_length=60),
        ),
    ]
